#!/usr/bin/env python3
"""Regenerate tests/data/geom_golden.txt from the Python reference evaluators.

The Python implementation (solid_diff/geom.py) is the ground truth for the Rust
port. This walks every sample part, evaluates every FACE surface and EDGE curve
at a fixed set of parameters, and writes the results as a flat text file that
tests/golden.rs replays through the Rust evaluators.

Run from the repo root:  .venv/bin/python rust/tests/gen_golden.py

One deliberate deviation from geom.py is baked in: BLENDED_EDGE `range[0]` is
taken as a magnitude (see BlendedEdge::from_node in src/geom/surfaces.rs).
"""

import os
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from solid_diff.brep2mesh import graphs_from_sldprt  # noqa: E402
from solid_diff.geom import BlendedEdge, make_curve, make_surface  # noqa: E402

OUT = Path(__file__).resolve().parent / "data" / "geom_golden.txt"

# canonical uv probes (parts are ~0.1 m, so v steps are small)
UV_PROBES = [(0.3, 0.002), (1.0, -0.001), (2.5, 0.005)]


def fmt(x):
    return repr(float(x))


def face_points(g, face):
    """Exact vertex coordinates on this face's boundary."""
    pts = []
    for lp in g.face_loops(face):
        for he in g.loop_halfedges(lp):
            v = g.deref(he.get("vertex"))
            if v:
                p = g.deref(v["point"])
                if p:
                    pts.append(np.asarray(p["pvec"], dtype=float))
    return pts[:4]


def emit_surface(out, sample, g, node):
    surf = make_surface(g, node)
    if surf is None:
        return
    if isinstance(surf, BlendedEdge) and surf.r < 0:
        surf.r = abs(surf.r)  # see module docstring
    rows = []
    for uv in UV_PROBES:
        p = surf.eval(np.array([uv]))[0]
        back = surf.inv(np.array([p]))[0]
        rows.append(("SE", uv[0], uv[1], p, back))
    for face in g.by_type("FACE"):
        if face.get("surface") != node["id"]:
            continue
        for p in face_points(g, face):
            uv = surf.inv(np.array([p]))[0]
            q = surf.eval(np.array([uv]))[0]
            rows.append(("SI", p[0], p[1], p[2], uv, q))
        break
    for r in rows:
        if r[0] == "SE":
            _, u, v, p, back = r
            out.write(
                f"SE {sample} {node['id']} {node['node_name']} {fmt(u)} {fmt(v)} "
                f"{fmt(p[0])} {fmt(p[1])} {fmt(p[2])} {fmt(back[0])} {fmt(back[1])}\n"
            )
        else:
            _, x, y, z, uv, q = r
            out.write(
                f"SI {sample} {node['id']} {node['node_name']} {fmt(x)} {fmt(y)} {fmt(z)} "
                f"{fmt(uv[0])} {fmt(uv[1])} {fmt(q[0])} {fmt(q[1])} {fmt(q[2])}\n"
            )


def emit_curve(out, sample, g, node):
    crv = make_curve(g, node)
    if crv is None:
        return
    try:
        t0, t1 = crv.full_range()
    except ValueError:
        t0, t1 = 0.0, 0.01
    for k in range(5):
        t = t0 + (t1 - t0) * k / 4.0
        p = crv.eval(np.atleast_1d(t))[0]
        back = crv.inv(p)
        out.write(
            f"C {sample} {node['id']} {node['node_name']} {fmt(t)} "
            f"{fmt(p[0])} {fmt(p[1])} {fmt(p[2])} {fmt(back)}\n"
        )


def main():
    OUT.parent.mkdir(parents=True, exist_ok=True)
    samples = sorted((ROOT / "samples").glob("*.SLDPRT"))
    with OUT.open("w") as out:
        out.write("# generated by rust/tests/gen_golden.py -- do not edit\n")
        for path in samples:
            try:
                graphs = graphs_from_sldprt(str(path))
            except Exception as exc:  # legacy OLE2 files
                print(f"skip {path.name}: {exc}", file=sys.stderr)
                continue
            _name, g = graphs[0]
            sample = os.path.basename(path)
            seen = set()
            for face in g.by_type("FACE"):
                sid = face.get("surface")
                if sid in seen or sid is None:
                    continue
                seen.add(sid)
                snode = g.deref(sid)
                if snode:
                    emit_surface(out, sample, g, snode)
            seen = set()
            for edge in g.by_type("EDGE"):
                cid = edge.get("curve")
                if cid in seen or cid is None:
                    continue
                seen.add(cid)
                cnode = g.deref(cid)
                if cnode:
                    emit_curve(out, sample, g, cnode)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
